# 检测人物动作是否结束定时任务
action_task: 0 0/1 * * * ?
# 游戏锁定
GamesTask: 0 */5 * * * ?
# 冲水堂清理
ExchangeTask: 0 50 20 * * ?
#关闭怪物
BossEndTask: 0 30 12,19 * * ?
# 修仙论坛
ForumTask: 0 0 4,16 * * ?
# 备份
AutoBackUpTask: 0 0 4 * * ?
#Cron表达式
