import Config from "./model/Config.js";
import index from './model/index.js';
const versionData = Config.getdefSet("version", "version");
let xiuxain = await index.toindex('apps');
let plugin = await index.toindex('plugins');
let apps={...xiuxain,...plugin};
logger.info(`__________________________`);
logger.info(`[修仙模拟器${versionData[0].version}]初始化！`);
logger.info(`答疑群：685979617`);
logger.info(`__________________________`);
export {apps};