- group: 
  list:
    - icon: help-icon_8
      title: "#降临世界 #再入仙途"
      desc: "创建存档，转世重生"
    - icon: help-icon_14
      title: "#改名张三 #设置道宣"
      desc: "修改道号,个性签名"
    - icon: help-icon_52
      title: "#储物袋 #升级储物袋"
      desc: "物品查询,容量提升"
    
- group: 
  list:
    - icon: help-icon_14
      title: "#闭关 #出关"
      desc: "进行闭关,增加修为"
    - icon: help-icon_21
      title: "#降妖 #归来"
      desc: "进行降妖,锻炼气血"

- group: 
  list:
    - icon: help-icon_21
      title: "#死斗+QQ/@道友"
      desc: "若在城里需决斗令"
    - icon: help-icon_22
      title: "#洗手"
      desc: "清魔力值"
    - icon: help-icon_39
      title: "#击杀+怪物名"
      desc: "随机掉落物品"
    - icon: help-icon_68
      title: "#探索怪物"
      desc: "查看所在地的怪物"


- group: 
  list:
    - icon: help-icon_51
      title: "#修仙地图"
      desc: "打开修仙世界大门"
    - icon: help-icon_43
      title: "#坐标信息"
      desc: "查看自己的坐标"
    - icon: help-icon_68
      title: "#位置信息"
      desc: "神识搜索位置"
    - icon: help-icon_33
      title: "#前往+位置名"
      desc: "前往指定位置"
    - icon: help-icon_33
      title: "#传送+区域名"
      desc: "随机降临区域"
    - icon: help-icon_33
      title: "#回到原地"
      desc: "取消走路行为"

- group: 
  list:
    - icon: help-icon_8
      title: "#基础信息"
      desc: "你的身世"
    - icon: help-icon_16
      title: "#面板信息"
      desc: "查看面板"
    - icon: help-icon_8
      title: "#突破"
      desc: "#破体"

- group: 
  list:
    - icon: help-icon_59
      title: "#学习+功法名"
      desc: "#忘掉+功法名"
    - icon: help-icon_44
      title: "#消耗+道具名"
      desc: "消耗道具"
    - icon: help-icon_12
      title: "#服用+丹药名"
      desc: "服用丹药"
    - icon: help-icon_16
      title: "#装备+装备名"
      desc: "#卸下+装备名"

- group: 
  list:
    - icon: help-icon_52
      title: "#置换所有物品"
      desc: "出售储物袋中所有物品"
    - icon: help-icon_52
      title: "#一键出售+物品类型"
      desc: "出售指定类型物品"
    - icon: help-icon_74
      title: "#赠送灵石1000 @道友"
      desc: "赠送灵石"