- group: 灵石设置
  list:
    - icon: help-icon_8
      title: "#发福利999"
      desc: "全服发放灵石"
    - icon: help-icon_8
      title: "#发补偿999@群友"
      desc: "单独发送灵石"
    - icon: help-icon_8
      title: "#扣除99999@群友"
      desc: "强行扣指定灵石"

- group: 怪物状态
  list:
    - icon: help-icon_8
      title: "#放出怪物"
      desc: "手动开启"
    - icon: help-icon_8
      title: "#关上怪物"
      desc: "手动关闭"

- group: 行为状态
  list:
    - icon: help-icon_9
      title: "#解封@群友"
      desc: "解除秘境/打工/闭关等状态"
    - icon: help-icon_9
      title: "#解除所有"
      desc: "解除全体时间动作状态"
    - icon: help-icon_9
      title: "#打入凡间@群友"
      desc: "关闭群友仙门，永不得返"

- group: 修仙管理
  list:
    - icon: help-icon_9
      title: "#修仙设置"
      desc: "查看修仙配置"
    - icon: help-icon_9
      title: "#清除冲水堂"
      desc: "全部回收物品"
    - icon: help-icon_9
      title: "#清除+编号"
      desc: "清除特定物品"
    - icon: help-icon_9
      title: "#打扫客栈"
      desc: "手动清理客栈消息"
    - icon: help-icon_9
      title: "#修仙世界"
      desc: "修仙分析统计"
    - icon: help-icon_14
      title: "#修仙更新"
      desc: "更新修仙模拟器插件"
    - icon: help-icon_14
      title: "#修仙强制更新"
      desc: "推荐使用强制更新"
